{% set name = "vscode-jupyter" %}
{% set version = "2021.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/microsoft/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 834fc0ae03d1d484620c9190017d942f621354b28df3146e80a351439f5094ea
  patches:
    - osx-arm64.patch  # [osx and arm64]

build:
  number: 0
  skip: true  # [win]
  ignore_run_exports:
    # node-canvas is built but not installed, so ignore its dependencies
    - cairo
    - giflib
    - libglib
    - libjpeg-turbo
    - pango
    - pixman

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - jq
  host:
    - python
    - pip <21
    - packaging
    - code-server >=3.9
    - gulp-cli
    - zeromq
    - vsce
    # As part of the build, we are compiling node-canvas from source
    - pixman
    - giflib
    - glib
    - cairo
    - pango
    - libjpeg-turbo
  run:
    - python
    - code-server >=3.9

test:
  commands:
    - code-server --list-extensions --show-versions | grep ms-toolsai.jupyter@{{ version }}

about:
  home: https://github.com/microsoft/vscode-jupyter
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - ThirdPartyNotices-Distribution.txt
    - ThirdPartyNotices-Repository.txt
    - extension_license.txt
  summary: VS Code Jupyter extension

extra:
  recipe-maintainers:
    - conda-forge/code-server
