{% set name = "vscode-jupyter" %}
{% set version = "2021.8.12" %}
{% set install_version = "2021.8.12" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/microsoft/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 1f672df5cd4ef7d3bf4b625f36a22474bcd053633357bc8b4ba72581fd9943ac
  patches:
    - osx-arm64.patch  # [osx and arm64]

build:
  number: 3
  skip: true  # [win]
  ignore_run_exports:
    # node-canvas is built but not installed, so ignore its dependencies
    - cairo
    - giflib
    - libglib
    - libjpeg-turbo
    - pango
    - pixman

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - jq
    - nodejs 14.*
  host:
    - python
    - pip <21
    - packaging
    - code-server >=3.9.2
    - gulp-cli
    - zeromq
    - vsce
    - nodejs 14.*
    # As part of the build, we are compiling node-canvas from source
    - pixman
    - giflib
    - glib
    - cairo
    - pango
    - libjpeg-turbo
  run:
    - python
    - code-server >=3.9.2

test:
  commands:
    - code-server --list-extensions --show-versions
    - code-server --list-extensions --show-versions | grep ms-toolsai.jupyter@{{ install_version }}

about:
  home: https://github.com/microsoft/vscode-jupyter
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - ThirdPartyNotices-Distribution.txt
    - ThirdPartyNotices-Repository.txt
  summary: VS Code Jupyter extension

extra:
  recipe-maintainers:
    - conda-forge/code-server
